# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Iris_ci_cd

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: pip install -r requirements.txt
  
    - name: Train
      run: python train.py 

    - name: Test_train
      run: python test_train.py

    - name: upload model
      uses: actions/upload-artifact@v4
      with: 
        name: Iris-model
        path: model/model.pkl

    - name: Monitor
      run: python monitor.py

    - name: Upload Data Drift
      uses: actions/upload-artifact@v4
      with: 
        name: drift-report
        path: model/drift_report.html 

        
